# Generated by Django 2.0.6 on 2018-06-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180614_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='band',
        ),
        migrations.RemoveField(
            model_name='album',
            name='user',
        ),
        migrations.RemoveField(
            model_name='band',
            name='user',
        ),
    ]
