# Generated by Django 2.0.6 on 2018-06-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180614_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='band',
        ),
    ]
