# Generated by Django 2.0.6 on 2018-06-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180614_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='band',
        ),
    ]
